name = "word30210/luau_hangul"
version = "0.2.1"
description = "A luau library for handling Hangul characters."
authors = ["word30210"]
repository = "https://github.com/Word30210/luau-hangul"
license = "MIT"
includes = ["src/**", "pesde.toml", "LICENSE", "README.md"]

[engines]
pesde = "^0.7.1"
lune = "^0.10.4"

[target]
environment = "luau"
lib = "src/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[dependencies]
super_table = { name = "word30210/super_table", version = "^0.1.0" }

[dev_dependencies]
frktest = { name = "itsfrank/frktest", version = "^0.0.2", target = "lune" }
multitarget = { name = "ewdev/multitarget", version = "^0.4.2-rc.7", target = "lune" }
darklua = { name = "pesde/darklua", version = "^0.17.2", target = "lune" }

[scripts]
build = "scripts/build.luau"
